package com.vneuron.cheese.order.service.domain;


public enum CheeseOrderEventEnum {
    VALIDATE_ORDER, CANCEL_ORDER, VALIDATION_PASSED, VALIDATION_FAILED,
    ALLOCATE_ORDER, ALLOCATION_SUCCESS, ALLOCATION_NO_INVENTORY, ALLOCATION_FAILED,
    CHEESEORDER_PICKED_UP
}
