DROP DATABASE IF EXISTS cheeseservice;
DROP USER IF EXISTS `cheese_service`@`%`;
CREATE DATABASE IF NOT EXISTS cheeseservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `cheese_service`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `cheeseservice`.* TO `cheese_service`@`%`;
FLUSH PRIVILEGES;